spring.datasource.url=jdbc:h2:mem:prgymdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop

jwt.secret=k9mP2xL8vQ4rT6wY1nB3cF7hJ5sD0aZ9uE2iO4gM8kW